apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my_app
  name: netology-web
  namespace: default
spec:
  containers:
  - name: netology-web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    # ports:
    # - containerPort: 8080